env: standard
runtime: nodejs18
service: default
instance_class: F2

handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  NODE_ENV: "production"
  GCP_ENV: "staging"
  NEXT_PUBLIC_GCP_ENV: "staging"
