import Document, { Html, Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
    render() {
        return (
            <Html>
                <Head>
                    <title>Your After .Life</title>

                    <meta name="title" content="Your After .Life" />
                    <meta name="description" content="Have you ever thought about Your After .Life?NO!?Don't worry! Many people don't think about it!But we did!Are you curious what we found out?" />
                    <meta name="keywords" content="after, life, death, God, heaven, hell, afterlife, after life, Bible, scripture, Christ" />
                    <meta name="robots" content="index, follow" />
                    <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
                    <meta name="language" content="English" />

                    <meta property="og:title" content="Your After .Life" />
                    <meta property="og:site_name" content="Your After .Life" />
                    <meta property="og:url" content="https://yourafter.life" />
                    <meta property="og:description" content="Have you ever thought about Your After .Life? NO!? Don't worry! Many people don't think about it! But we did! Are you curious what we found out?" />
                    <meta property="og:type" content="article" />
                    <meta property="og:image" content="https://yourafter.life/yal-logo.png" />


                    {/* Global Site Tag (gtag.js) - Google Analytics */}
                    <script
                        async
                        src={`https://www.googletagmanager.com/gtag/js?id=G-JVFDC7YLM5`}
                    />
                    <script
                        dangerouslySetInnerHTML={{
                            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-JVFDC7YLM5', {
              page_path: window.location.pathname,
            });
          `,
                        }}
                    />
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/yal-logo.png" />
                </Head>
                <body>
                    <Main />
                    <NextScript />
                </body>
            </Html>
        )
    }
}
